sudo apt update
sudo apt install docker.io
sudo apt install docker-compose
nano docker-compose.yaml
docker-compose up -d
docker-compose down
---------------------------------------------------------------
(or) this method to use.......
sudo usermod -aG docker $(whoami)
newgrp docker
docker run hello-world
sudo systemctl status docker
sudo systemctl start docker
docker-compose --version
docker-compose logs
sudo docker-compose up -d
-------------------------------------------------------------------
version: '3'

services:
  javaapp:
    image: mixaverross88/dockerize_java_mysql_example_project
    ports:
      - 8083:8080
  mysqlapp:
    image: mixaverross88/dockerize_java_mysql_example_project_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret 
    ports:
      - 3311:3306
